boot.o: boot.S multiboot.h x86_desc.h types.h
int_asm_link.o: int_asm_link.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesys.o: filesys.c filesys.h types.h lib.h terminal.h
i8259.o: i8259.c i8259.h types.h lib.h terminal.h
idt_handlers.o: idt_handlers.c idt_handlers.h x86_desc.h types.h \
  int_asm_link.h i8259.h lib.h terminal.h rtc.h keyboard.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h terminal.h \
  i8259.h debug.h tests.h rtc.h keyboard.h idt_handlers.h paging.h \
  filesys.h
keyboard.o: keyboard.c keyboard.h lib.h types.h terminal.h i8259.h
lib.o: lib.c lib.h types.h terminal.h
paging.o: paging.c paging.h types.h x86_desc.h
rtc.o: rtc.c idt_handlers.h x86_desc.h types.h lib.h terminal.h i8259.h \
  rtc.h
terminal.o: terminal.c terminal.h lib.h types.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h terminal.h rtc.h \
  filesys.h
